[package]
name = "perfcnt_bench"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
perfcnt = "0.7.1"
libc = "*"